#!/bin/bash
########## Variables

# check not run by root
if [ "$(id -u)" == "0" ]; then
  echo "Do not run this script as root" 1>&2
  exit 1
fi

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
# list of files/folders to symlink in homedir without trailing slash
files=".bash_profile .bashrc .gitconfig .gitignore .git-completion.bash .git_templates .hushlogin .tern-config tmux .tmux.conf .osx .vim .vimrc z.sh"

##########

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/$file
done

source ~/.bashrc
source ~/.bash_profile
