#!/bin/bash

if [[ -z "$SWAYSOCK" ]]; then
    xrandr --output HDMI-1 --scale 1.5x1.5 --rate 144 --output eDP-1 --off
    # load keyboard config when connecting to home setup
    xmodmap ~/.Xmodmap
    $HOME/dotfiles/scripts/bg
    i3-msg restart
else
    swaymsg output HDMI-A-1 mode 2560x1440 scale 1
    swaymsg output eDP-1 disable
fi
