-- require('config/lsp')
require('config/completion')
require('config/gitsigns')
require('config/go')
require('config/lsp')
require('config/lualine')
require('config/neogen')
require('config/oil')
require('config/options')
require('config/snippets')
require('config/theme')
require('config/todo')
require('config/treesitter')
require('config/treesitter_context')
require('config/trouble')
