-- load options before lazy
require('config/options')
require('config/lazy')
require('config/keybinds')
-- require('config/completion')
-- require('config/comments')
-- require('config/gitsigns')
-- require('config/go')
-- require('config/keybinds')
-- require('config/lsp')
-- require('config/lualine')
-- require('config/neogen')
-- require('config/neckpain')
-- require('config/oil')
-- require('config/snippets')
-- require('config/theme')
-- require('config/todo')
-- require('config/treesitter')
-- require('config/treesitter_context')
-- require('config/trouble')
