#!/bin/bash

yaourt -S compton
yaourt -S rofi
yaourt -S feh
yaourt -S scrot
yaourt -S betterlockscreen-git
yaourt -S imagemagick
yaourt -S the_silver_searcher
yaourt -S diff-so-fancy
yaourt -S tldr
yaourt -S docker
